### ISSUE TITLE
Comprimir los datos

### ISSUE THREAD

**Issue by joromero** [nachovalde/Patos#2]
Necesitamos comprimir los datos. grafos con strings no funcionan muy bien porque son demasiado grandes asi que cree ActorCompressor, alguien puede intentar correrlo en el output despues de la primera etapa?

**Comment by nachovalde** [comment]
Yo lo puedo hacer pero en la tarde, ahí les cuento como anda

El viernes, 31 de julio de 2015, joromero notifications@github.com
escribió:

> Necesitamos comprimir los datos. grafos con strings no funcionan muy bien
> porque son demasiado grandes asi que cree ActorCompressor, alguien puede
> intentar correrlo en el output de la parte 1?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nachovalde/Patos/issues/2.

## 

Ignacio Valderrama Lorca
Estudiante Ingenieria de la Universidad de Chile

**Comment by moishernadez** [comment]
funcionó? Yo estoy avanzando en el informe ahora...
